
%%-----G2O specification---
type_VERTEX_XY = 'VERTEX_XY';
type_VERTEX_SE2 = 'VERTEX_SE2';
% type_ROBOTLASER1 = 'ROBOTLASER1';
type_EDGE_SE2 = 'EDGE_SE2';
type_EDGE_BEARING_SE2_XY = 'EDGE_BEARING_SE2_XY';
type_EDGE_SE2_XY = 'EDGE_SE2_XY';

type_VERTEX_TRACKXYZ = 'VERTEX_TRACKXYZ';
type_EDGE_SE3_TRACKXYZ = 'EDGE_SE3_TRACKXYZ';
type_VERTEX_SE3_QUAT = 'VERTEX_SE3:QUAT';
type_EDGE_SE3_QUAT = 'EDGE_SE3:QUAT';
type_PARAMS_SE3OFFSET = 'PARAMS_SE3OFFSET';
